name: Java CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "**.h"
      - "**.c"
      - "**.java"
      - ".github/workflows/**"
      - "**.properties"
      - "**.xml"

jobs:
  release:
    needs: [test-with-Java-7-and-later]
    name: Release if requested
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && endsWith(github.event.head_commit.message, 'Release new version')
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: 'zulu'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to the Maven central repository
        run: |
          export GPG_TTY=$(tty)
          echo "${{ secrets.gpg_private_key }}" | gpg --batch --import
          git config user.name "toolfactory"
          git config user.email "tool.factory.heads@gmail.com"
          git config pull.rebase false
          git pull origin ${{github.ref}}
          mvn -B release:prepare release:perform -Dproject_jdk_version=8 -DskipTests=true \
             -Dgpg.passphrase="${{ secrets.gpg_passphrase }}" \
             -Dgpg.keyname=${{ secrets.gpg_key_id }} \
             -Drepository.url=https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        env:
          MAVEN_USERNAME: ${{ secrets.nexus_username }}
          MAVEN_PASSWORD: ${{ secrets.nexus_password }}
